package com.SpriteSheeter.Enums;

public enum SubWindowOptionsEnum {
    CORRUPTED_FILE,
    HELP,
    INVALID_IMAGE,
    INVALID_IMAGE_PATH,
    INVALID_LAYER_HELP,
    INVALID_PATH,
    INVALID_SCALE,
    INVALID_TEXT,
    SHEET_AND_SPRITE,
    SPRITESHEET_FAIL,
    SPRITE_SIDE_FAIL,
    SQUARE_ERROR,
    UNSUPPORTED_IMAGE
}
